import { test, expect } from '@playwright/test';

// Security regression test — generated by VibeAudit
// Ensures BOLA vulnerability on /api/orders/cmpk8f2hn0003jbvh0q62ocdc stays fixed
// If this test fails, the authorization check has been removed
//
// Sensitive fields that must NOT be exposed to non-owners:
//   - address (PII)

const emailB = process.env.TEST_USER_B_EMAIL;
const passwordB = process.env.TEST_USER_B_PASSWORD;

if (!emailB || !passwordB) {
  throw new Error(
    'TEST_USER_B_EMAIL and TEST_USER_B_PASSWORD must be set ' +
    'as environment variables before running generated tests. ' +
    'Never commit credentials.'
  );
}

test.describe('BOLA Regression: /api/orders/cmpk8f2hn0003jbvh0q62ocdc', () => {
  test('attacker cannot access victim record cmpk8f2hn0003jbvh0q62ocdc', async ({ request }) => {
    // Step 1: Authenticate as attacker (User B)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: emailB,
        password: passwordB,
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Attempt to access victim's record using attacker session
    const attackRes = await request.get('/api/orders/cmpk8f2hn0003jbvh0q62ocdc', {
      headers: { Cookie: cookies },
    });

    // Step 3: Must return 403 Forbidden — not 200
    expect(attackRes.status()).toBe(403);

    // Step 4: Response body must not contain victim's sensitive data
    const body = await attackRes.json().catch(() => ({}));
    expect(body.address).toBeUndefined();
  });

  test('owner can still access their own record', async ({ request }) => {
    const emailA = process.env.TEST_USER_A_EMAIL;
    const passwordA = process.env.TEST_USER_A_PASSWORD;

    if (!emailA || !passwordA) {
      throw new Error(
        'TEST_USER_A_EMAIL and TEST_USER_A_PASSWORD must be set ' +
        'as environment variables before running generated tests. ' +
        'Never commit credentials.'
      );
    }

    // Step 1: Authenticate as victim (record owner)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: emailA,
        password: passwordA,
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Access own record
    const res = await request.get('/api/orders/cmpk8f2hn0003jbvh0q62ocdc', {
      headers: { Cookie: cookies },
    });

    // Step 3: Owner should still get 200
    expect(res.status()).toBe(200);
  });
});
